[package]
name = "deco"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
quote = "0.5"
proc-macro2 = "0.3"

[dependencies.syn]
version = "0.13"
features = ["full", "extra-traits"]

