[package]
name = "deco"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.4"
syn = { version = "1.0.20", features = ["full", "extra-traits"] }
