[package]
name = "pydeco"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.4"
proc-macro2 = "1.0.12"
syn = { version = "1.0.20", features = ["full", "extra-traits"] }
anyhow = "1.0.28"
